// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: utils.proto

#include "utils.pb.h"
#include "utils.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace utils {

static const char* UtilServer_method_names[] = {
  "/utils.UtilServer/Sort",
  "/utils.UtilServer/FindMin",
  "/utils.UtilServer/FindMax",
};

std::unique_ptr< UtilServer::Stub> UtilServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< UtilServer::Stub> stub(new UtilServer::Stub(channel));
  return stub;
}

UtilServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Sort_(UtilServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindMin_(UtilServer_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindMax_(UtilServer_method_names[2], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status UtilServer::Stub::Sort(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::utils::DoubleArray* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Sort_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::utils::DoubleArray>* UtilServer::Stub::AsyncSortRaw(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::utils::DoubleArray>::Create(channel_.get(), cq, rpcmethod_Sort_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::utils::DoubleArray>* UtilServer::Stub::PrepareAsyncSortRaw(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::utils::DoubleArray>::Create(channel_.get(), cq, rpcmethod_Sort_, context, request, false);
}

::grpc::Status UtilServer::Stub::FindMin(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::utils::Double* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_FindMin_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::utils::Double>* UtilServer::Stub::AsyncFindMinRaw(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::utils::Double>::Create(channel_.get(), cq, rpcmethod_FindMin_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::utils::Double>* UtilServer::Stub::PrepareAsyncFindMinRaw(::grpc::ClientContext* context, const ::utils::DoubleArray& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::utils::Double>::Create(channel_.get(), cq, rpcmethod_FindMin_, context, request, false);
}

::grpc::ClientWriter< ::utils::Double>* UtilServer::Stub::FindMaxRaw(::grpc::ClientContext* context, ::utils::Double* response) {
  return ::grpc::internal::ClientWriterFactory< ::utils::Double>::Create(channel_.get(), rpcmethod_FindMax_, context, response);
}

::grpc::ClientAsyncWriter< ::utils::Double>* UtilServer::Stub::AsyncFindMaxRaw(::grpc::ClientContext* context, ::utils::Double* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::utils::Double>::Create(channel_.get(), cq, rpcmethod_FindMax_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::utils::Double>* UtilServer::Stub::PrepareAsyncFindMaxRaw(::grpc::ClientContext* context, ::utils::Double* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::utils::Double>::Create(channel_.get(), cq, rpcmethod_FindMax_, context, response, false, nullptr);
}

UtilServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UtilServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UtilServer::Service, ::utils::DoubleArray, ::utils::DoubleArray>(
          std::mem_fn(&UtilServer::Service::Sort), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UtilServer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UtilServer::Service, ::utils::DoubleArray, ::utils::Double>(
          std::mem_fn(&UtilServer::Service::FindMin), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UtilServer_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< UtilServer::Service, ::utils::Double, ::utils::Double>(
          std::mem_fn(&UtilServer::Service::FindMax), this)));
}

UtilServer::Service::~Service() {
}

::grpc::Status UtilServer::Service::Sort(::grpc::ServerContext* context, const ::utils::DoubleArray* request, ::utils::DoubleArray* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UtilServer::Service::FindMin(::grpc::ServerContext* context, const ::utils::DoubleArray* request, ::utils::Double* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UtilServer::Service::FindMax(::grpc::ServerContext* context, ::grpc::ServerReader< ::utils::Double>* reader, ::utils::Double* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace utils

